const shopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL: 'FETCH_COLLECTIONS_FAIL'
}

export default shopActionTypes;